EXP:
  exp_name: &exp_name scanobjectnn_cls_curvenet
  log_dir: &log_dir logs/
  # config_dir: configs/config.yaml

DATA:
  data_name: scanobjectnn #modelnet40 # scanobjectnn  # s3dis
  data_dir: data/
  num_point: 1024
  batch_size: 32  # batch size for training
  test_batch_size: 32  # batch size for validation during training, memory and speed tradeoff
  workers: 8  # data loader workers

MODEL:
  num_classes: 15 # 15

TRAIN:
  model_name: curvenet
  model_copy_name: model_0
  print_model: False
  learning_rate: 0.1
  epochs: 200
  

Distributed:
  gpu: 0
  dist_url: tcp://localhost:8888
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test_list: dataset/s3dis/list/val5.txt
  test_list_full: dataset/s3dis/list/val5_full.txt
  split: val  # split in [train, val and test]
  test_gpu: [0]
  test_workers: 4
  batch_size_test: 4
  model_path:
  save_folder:
  names_path: data/s3dis/s3dis_names.txt
Logger:
  logger_filename: train.log